# Build Stage
FROM golang:1.24 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o node node_main.go node_redis.go

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y redis-server ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/node .
COPY start.sh .

RUN chmod +x start.sh

ENV REDIS_ADDR=localhost:6379
ENV CENTRAL_REDIS_ADDR=35.200.253.69:6380
ENV PORT=5000
ENV SERVER_URL=http://35.200.253.69:5000/

EXPOSE 5000 6379 6380

ENTRYPOINT ["./start.sh"]
